name:       csvdsl
version:    0.1.0.0
github:     "githubuser/example-name"
license:    BSD-3-Clause
author:     "Author name here"
maintainer: "example@example.com"
copyright:  "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package:
# synopsis: Short description of your package
# category: Web

description: Alex and Happy project.

dependencies:
- base >= 4.7 && < 5
- array
- split >=0.2.3.4
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  verbatim: |
    build-tool-depends:
      alex:alex,
      happy:happy

executables:
  csvdsl: 
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csvdsl

tests:
  csvdsl-test: 
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csvdsl
